### ISSUE TITLE
Too much weaponry mods?

### ISSUE THREAD

**Issue by BoraiperXD** [Globox1997/MedievalWeapons#10]
Mods I used:
MC Dungeons Weapons
MC Dungeons Armors
MC Story Mode Armors
Better End

[crash-2021-03-07_13.19.30-server.txt](https://github.com/Globox1997/MedievalWeapons/files/6096595/crash-2021-03-07_13.19.30-server.txt)

here

**Comment by Globox1997** [comment]
[medievalweapons-1.0.8-test.zip](https://github.com/Globox1997/MedievalWeapons/files/6096847/medievalweapons-1.0.8-test.zip)
please test this (you have to unzip the file)

**Comment by BoraiperXD** [comment]
It's working 100% and no crash i glad i can play survival world now ty!

**Comment by Globox1997** [comment]
alright, gonna update it on cf later :)
