### ISSUE TITLE
Unbalanced Sickle

### ISSUE THREAD

**Issue by GanksNRoses** [Globox1997/MedievalWeapons#100]
Make the sickle 1.8 Atk speed instead of 1.7 cause it gets outclassed by everything else

**Comment by Globox1997** [comment]
Increased sickle attack spd with [https://github.com/Globox1997/MedievalWeapons/commit/8b5446b179a3aee610855e79697429227cc1b66b](https://github.com/Globox1997/MedievalWeapons/commit/8b5446b179a3aee610855e79697429227cc1b66b)
