### ISSUE TITLE
[Bug] Javelin can have any enchantment now

### ISSUE THREAD

**Issue by Flyvee** [Globox1997/MedievalWeapons#104]
The javelin, while no longer causing a crash, now can be enchanted with any enchantment possible.
![2023-02-23_22 29 14](https://user-images.githubusercontent.com/30793646/221023084-28134847-6f96-45d1-9803-a1698efc6c44.png)
Here is an example of one containing sword, fishing rod, crossbow and armor enchantments.

**Comment by Flyvee** [comment]
I just found out though that in the previous update, it could be enchanted with any enchantment then too, just that the incompatible ones like protection wouldn't have an effect, but others like loyalty does work.

**Comment by Globox1997** [comment]
Thanks for reporting this, fixed with [https://github.com/Globox1997/MedievalWeapons/commit/1c9f4891e27da2c8660396afe28e714b10452351](https://github.com/Globox1997/MedievalWeapons/commit/1c9f4891e27da2c8660396afe28e714b10452351)
