### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Hyxth** [Globox1997/MedievalWeapons#106]
.

**Comment by Globox1997** [comment]
This sounds really odd, which weapons are unaffected?

**Comment by Hyxth** [comment]
The breakpoints for one-shotting a zombie calls for 8 attack damage and smite V(5). when i applied smite 5 to all weapons, the results were as follows:
Weapons that were UNaffected by the smite V enchantment: Diamond mace, netherite rapier, and stone longsword.
Weapons that were affected by smite V: Stone war axe, netherite lance, netherite sword, and iron battleaxe.
(unsure if material matters but i'm specifying anyways)
I made a new instance and only added medieval weapons mod dependencies, medieval weapons mod itself, and everything worked fine. do you know of any mod incompatibilities the collide with medieval weapons?

**Comment by JasdanVM** [comment]
You still have this problem?

**Comment by Hyxth** [comment]
> You still have this problem?

as i stated before, the mod works fine by itself, yes. but there appears to be a conflicting mod i have. this is why i originally asked if there were any known mods that could conflict with this. the developer obviously isn't interested in helped based off the lack of response to if they knew of any mods that could conflict though, and also because the mod works fine **by itself**. maybe it's better combat? I'm not sure what it would specifically be doing to affect enchantments on medieval weapons though. it might also be a dependency but i wouldn't know.
I guess this isn't really the right place to be talking about mod conflicts, since that's a mostly a me issue, but it's still important information for future people know what can and cannot be used with this mod.

this is the list of mods i have:

Architectury API (Fabric/Forge) - (BASIC DEPENDANCY)
Arrp (MEDIEVALWEAPONS DEPENDANCY)
Cardinal Components - (ORIGINS DEPENDANCY)
Cloth Config API (Fabric/Forge) - (BASIC DEPENDANCY)
CreativeCore (TOWNS AND TOWERS DEPENDANCY | ENHANCEDVISUALS DEPENDANCY)
Collective (SKELETON HORSE SPAWN DEPENDANCY)
Fabric API - (BASIC DEPENDANCY)
GeckoLib (BASIC DEPENDANCY)
Lithium (Fabric) - (SODIUM DEPENDANCY)
MidnightLib (ICARUS DEPENDANCY | IT TAKES A PILLAGE (FABRIC))
Mod Menu - (CHARM DEPENDANCY)
Pehkui - (ORIGINS DEPENDANCY)
Phosphor (Fabric) - (SODIUM DEPENDANCY)
PlayerAbilityLib - (ORIGINS DEPENDANCY)
Sound Categories (EXTRA SOUNDS DEPENDANCY)
TerraBlender (Fabric) - (OH THE BIOMES YOU'LL GO REFABRICTAED DEPENDANCY)
Trinkets (Fabric) - (ICARUS DEPENDANCY | BETTER ANIMALS PLUS DEPENDANCY)
bendy-lib - (BETTER COMBAT DEPENDANCY)
playerAnimator - (BETTER COMBAT DEPENDANCY)
Appleskin
Better Combat
Better Animals Plus
Brewin' And Chewin' [Fabric]
Chef's Delight [Fabric]
Clumps
Connectivity[Forge/Fabric]
Dramatic Doors
Ecologics
ExtraSounds
EnhancedVisuals
Extra Origins
Farmer's Delight [Fabric]
Guard Villagers (Fabric/Quilt)
Icarus
Interactic
It Takes a Pillage (Fabric)
JourneyMap
JourneyMap Tools
Medieval Origins
MedievalWeapons
MemoryLeakFix
Oh The Biomes You'll Go Refabricated
Origins (Fabric)
Rotten Creatures
Regrowth
Roughly Enough Items Fabric/Forge (REI)
RPG Origins
Scout
Sodium
Structory
Swampier Swamps (Fabric)
Skeleton Horse Spawn
Towns and Towers
Tool Leveling+ [Fabric]
You're in Grave Danger

**Comment by Globox1997** [comment]
Not answering can mean a couple of things but I expect people to find mod incompats to debug and find the incompatible mod and than I can help, otherwise the incompatibility has to get accepted - time is limited

**Comment by Globox1997** [comment]
Reopen if you figure out which mod leads to this bug.
