### ISSUE TITLE
Arrp, Brrp is there a fix yet?

### ISSUE THREAD

**Issue by NetunooOG** [Globox1997/MedievalWeapons#107]
This problem been mentioned a few times, but I love this mod so much I had to. Brrp, arrp compatibility issues. I can get them to run together and it loads/functions kinda, after about 10min if your lucky maybe 20m all the mobs will start sludging around all slow mo even if your hitting +60fps. but If I run just brrp I have no issues with animation with entities. Only arrp has semi laggy mobs but not as bad as with both in mods folder. Ran a test overnight just to see if when I wake up if game would crash or mobs would slug around. Game was smooth and clean with out arrp. BUT MISSING TEXTURES! I really dont want to but for now uninstalling this amazing mod ;(. By far the best weapons pack mod available for 1.19.2

**Comment by Globox1997** [comment]
Appreciate it :)
With the latest version (1.20.1) you can run either BRRP or ARRP with this mod but not both at the same time.
