### ISSUE TITLE
francisca bug

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [Globox1997/MedievalWeapons#112]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

1.4.5

### Describe the Issue

i cant throw the francisca

### latest.log

https://drive.google.com/file/d/1fN5Se2Le_zZfH8AFig08ofFRBIiei2nA/view?usp=sharing

### Do you use any other mods except the required ones?

yes

**Comment by Globox1997** [comment]
the drive is empty. Reopen with the latest log.
