### ISSUE TITLE
Hi, how do I upgrade this mod's weapon from diamond to netherite?

### ISSUE THREAD

**Issue by ender0416** [Globox1997/MedievalWeapons#114]
### Minecraft Version

1.20.x

### Mod Loader Version

1.20

### Mod Version

1.4.5

### Describe the Issue

The vanilla template doesn't seem to work?
I checked the REI recipe and the upgrade recipe shows that the template slot supposed to be a netherite's weapon version of the weapon I want to upgrade.
So is it a bug? Or its designed like you can't get it in survival.

### latest.log

[latest.log](https://github.com/Globox1997/MedievalWeapons/files/12179086/latest.log)

**Comment by Globox1997** [comment]
Whoops, this was not intentionally xD.
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/d1dd6f4f7bea0dcf8d510aba26981f124853e342](https://github.com/Globox1997/MedievalWeapons/commit/d1dd6f4f7bea0dcf8d510aba26981f124853e342)
