### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by Voidhydra678** [Globox1997/MedievalWeapons#115]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

When will this be updated to work in version 1.20.1?
Thanks

**Comment by dninemfive** [comment]
Additional information: version 1.4.5 of the mod is labelled as supporting 1.20.1 on Modrinth, but the jar file has not been updated to reflect this. The game crashes with the message "Medieval Weapons requires version 1.20 of minecraft, but only a different version is present: 1.20.1" when attempting to launch on 1.20.1.

**Comment by Globox1997** [comment]
Uploaded an update.
