### ISSUE TITLE
[Compatibility Request] Deeper and Darker Support, Enderite Support

### ISSUE THREAD

**Issue by federkey** [Globox1997/MedievalWeapons#117]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Could it be possible to have working weapons for the Enderite and Warden materials? I'm no code expert, just asking for a modpack

**Comment by Globox1997** [comment]
Please provide the textures for this compatibility.

**Comment by federkey** [comment]
[warden textures for medieval weapons.zip](https://github.com/Globox1997/MedievalWeapons/files/12376016/warden.textures.for.medieval.weapons.zip)

If I provided more textures for the ender dragon mob from Adventure Z, would it be possible to have variant textures for it when spawning? I think that would be nice in multiplayer environments, so that every player has its own dragon.

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/MedievalWeapons/commit/4fbb8ff61289c3965b9bad5c923f964d7d2f64c3](https://github.com/Globox1997/MedievalWeapons/commit/4fbb8ff61289c3965b9bad5c923f964d7d2f64c3)
