### ISSUE TITLE
[Compatibility Request] Paradise Lost Support

### ISSUE THREAD

**Issue by federkey** [Globox1997/MedievalWeapons#119]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

i made textures for the olvite set from the paradise lost, could they be added into the mod? thanks
[olvite textures for medieval weapons.zip](https://github.com/Globox1997/MedievalWeapons/files/12394492/olvite.textures.for.medieval.weapons.zip)

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/MedievalWeapons/commit/4fbb8ff61289c3965b9bad5c923f964d7d2f64c3](https://github.com/Globox1997/MedievalWeapons/commit/4fbb8ff61289c3965b9bad5c923f964d7d2f64c3)
