### ISSUE TITLE
Compabilty: BetterNether and BetterEnd

### ISSUE THREAD

**Issue by Blunder-G** [Globox1997/MedievalWeapons#12]
Compatibility for BetterEnd and BetterNether ores. I love both mods very much, but it hurts me that the weapons are incompatible.

**Comment by Globox1997** [comment]
Added compat :) [https://github.com/Globox1997/MedievalWeapons/commit/5ea665fe41ade3c57ce9544978cd709ed430ef9e](https://github.com/Globox1997/MedievalWeapons/commit/5ea665fe41ade3c57ce9544978cd709ed430ef9e)
