### ISSUE TITLE
[1.20.1] CRASH: Upgrading Medieval Weapons to Netherite with Better Nether installed

### ISSUE THREAD

**Issue by DeshiDesu** [Globox1997/MedievalWeapons#120]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

medievalweapons-1.4.7.jar

### Describe the Issue

**Issue:** Placing weapons from the Medieval Weapons into the smithing table slot, the game crashes with the following message:

> Description: mouseReleased event handler
> 
> java.lang.AbstractMethodError: Receiver class net.medievalweapons.item.Long_Sword_Item does not define or inherit an implementation of the resolved method 'abstract void putEnchantments(net.minecraft.class_1799, java.util.Map)' of interface org.betterx.betternether.interfaces.InitialStackStateProvider.
	at net.minecraft.class_8060.handler$zfb000$betternether$bcl_assemble(class_8060.java:540)
	at net.minecraft.class_8060.method_8116(class_8060.java)
	at net.minecraft.class_4862.method_24928(class_4862.java:100)
	at net.minecraft.class_4861.method_7609(class_4861.java:106)
	at net.minecraft.class_4861$3.method_5431(class_4861.java:96)
	at net.minecraft.class_1277.redirect$baa000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:543)

This only occurs with BetterNether installed, probably a compat issue again.

**Without BetterNether:**
![2023-08-30_14 57 12](https://github.com/Globox1997/MedievalWeapons/assets/120287925/862511ab-bc72-42ab-963e-12c7849b6f49)

### latest.log

[crash-2023-08-30_14.59.34-client.txt](https://github.com/Globox1997/MedievalWeapons/files/12479321/crash-2023-08-30_14.59.34-client.txt)

### Do you use any other mods except the required ones?

better-nether-9.0.9.jar
cloth-config-11.1.106-fabric.jar
bclib-3.0.13.jar

**Comment by xR4YM0ND** [comment]
For Record: BetterNether has now 2 different sets instead of one.

They also changed names and enchantments

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/cd81b95686cd3ee585797fe3fcd9118486bc633c](https://github.com/Globox1997/MedievalWeapons/commit/cd81b95686cd3ee585797fe3fcd9118486bc633c)
