### ISSUE TITLE
Current Mythic Upgrades compatibility is broken since version 2.3.0+

### ISSUE THREAD

**Issue by CyberSteve777** [Globox1997/MedievalWeapons#123]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.23

### Mod Version

1.4.7+1.20.1

### Describe the Issue

In your compat you are relying on our old [ModToolMaterials](https://github.com/Globox1997/MedievalWeapons/blob/4fbb8ff61289c3965b9bad5c923f964d7d2f64c3/src/main/java/net/medievalweapons/compat/CompatItems.java#L22) enum, which is causing crash on startup.
To fix this bug, you simply should change current enum name to `MUToolMaterials`, as [here](https://github.com/TriQue06/mythic-upgrades-1.20.x/blob/dev-1.20.1/src/main/java/net/trique/mythicupgrades/item/MUToolMaterials.java)

### latest.log

not needed

### Do you use any other mods except the required ones?

no

**Comment by Globox1997** [comment]
Will be easy :)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/6d8f937b40a6004d3c8564ee10c04a3c9e393449](https://github.com/Globox1997/MedievalWeapons/commit/6d8f937b40a6004d3c8564ee10c04a3c9e393449)
