### ISSUE TITLE
Assist Creating Custom resource packs

### ISSUE THREAD

**Issue by Merith-TK** [Globox1997/MedievalWeapons#13]
So my server we are trying to have modded weapons have custom textures for lore, but we cant see to successfully modify the resources, could you make a guide for this?

**Comment by Globox1997** [comment]
It is basically done like with vanilla just another path [https://minecraft.fandom.com/wiki/Tutorials/Creating_a_resource_pack](https://minecraft.fandom.com/wiki/Tutorials/Creating_a_resource_pack) :)
This mod adds entities for some weapons like the big axe (staff of healing, mace, francisca, javelin, lance and thalleous sword) which can't get changed with a ressource pack or at least not the ingame held item, all other weapons can get changed.

**Comment by Merith-TK** [comment]
Why does it use entities? im curious

**Comment by Globox1997** [comment]
To correct my self: only the javelin and the francisca are using entities because you can throw them just as the trident in your world.
The other items I mentioned have custom hardcoded models because their inventory items differ to the handheld item

**Comment by Merith-TK** [comment]
Is there a way you could make it easier to modify the models for texture
packs.

**Comment by Globox1997** [comment]
I tried to but it's not too easy to get done and since the mod goal is to represent the songs of war series it does already a pretty good job with the textures/models. 
Another side effect is messing around with the renderer mechanic can break shader compat

**Comment by Skeithh** [comment]
Are there plans to perhaps still add the ability to do this? While we love the base textures, just like person that opened this ticket- we often use items from the mod as mechanic bases for lore-related weapons. Right now if we want to have anything fancy mechanics-wise we're unfortunately just limited to having a longsword for every lore weapon.

**Comment by Merith-TK** [comment]
hmm... why not include BlockBench Model files for the textures and models?

**Comment by Globox1997** [comment]
Yes, tried another time but I can't get it to work, if some of you guys have coding knowledge and can help, I appreciate it a lot :)

**Comment by Globox1997** [comment]
So I gave it a third shot and now I got a solution :)
In the next update you will be able to change all textures and don't have to use models

**Comment by Globox1997** [comment]
So this is now possible with the latest update :)
I'm generating models on runtime now but those can get overridden by resource packs.
