### ISSUE TITLE
"Watch out for Stone Francisca! It's a game-crasher when it comes to taking down pigs !"

### ISSUE THREAD

**Issue by SheanlR** [Globox1997/MedievalWeapons#138]
### Minecraft Version

1.21.x

### Mod Loader Version

fabric 0.16.5

### Mod Version

1.4.8

### Describe the Issue

I threw a **_stone francisca_** at a **_pig_**, and then the game crashed.

### latest.log

[crash-2024-09-16_16.15.24-server.txt](https://github.com/user-attachments/files/17010213/crash-2024-09-16_16.15.24-server.txt)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/673fcb245f4648d45e15df5d43995723d9d35635](https://github.com/Globox1997/MedievalWeapons/commit/673fcb245f4648d45e15df5d43995723d9d35635)
