### ISSUE TITLE
Crashes if installed with better nether.

### ISSUE THREAD

**Issue by Torathion** [Globox1997/MedievalWeapons#139]
### Minecraft Version

1.21.x

### Mod Loader Version

Fabric 0.16.5

### Mod Version

Latest

### Describe the Issue

I can't start the game, because for some reason, better nether doesn't like this mod again.

Modrinth crash report: https://mclo.gs/cxDQ90x

### latest.log

Modrinth log: https://mclo.gs/aKQMfqL

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/7a54abd84776c7b78ac31ac38611dd487c3a85bd](https://github.com/Globox1997/MedievalWeapons/commit/7a54abd84776c7b78ac31ac38611dd487c3a85bd)
