### ISSUE TITLE
Wiki page link not working

### ISSUE THREAD

**Issue by FASTB1mc** [Globox1997/MedievalWeapons#141]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug/feature.

### Description of your suggestion.

The wiki page link on modrinth is not working. It just keeps saying that the Site can't be reached. Please fix this because I want to know how to get the thallous sword. 
Thanks.

**Comment by Globox1997** [comment]
Fixed the link
