### ISSUE TITLE
Crashes On 1.21.1

### ISSUE THREAD

**Issue by Fyoncle** [Globox1997/MedievalWeapons#144]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.9

### Mod Version

 1.5.0+1.21.1

### Describe the Issue

It crashing on launch.

### latest.log

https://mclo.gs/dFRO17p

**Comment by Globox1997** [comment]
Pls look though your log before you open a github issue :)
It tells you usually what the issue is: MedievalWeapons requires ARRP or BRRP as a mod dependencys! on line 17.

**Comment by Fyoncle** [comment]
> Pls look though your log before you open a github issue :) It tells you usually what the issue is: MedievalWeapons requires ARRP or BRRP as a mod dependencys! on line 17.

Wdym? There is no mod called ARRP

**Comment by Fyoncle** [comment]
![image](https://github.com/user-attachments/assets/bff8a20b-5162-4017-941d-3c6f29ec27fc)
It doesn't exist for 1.21.1
