### ISSUE TITLE
YES ME AGAIN: BYG and Aether compat (But there is an issue...)

### ISSUE THREAD

**Issue by Blunder-G** [Globox1997/MedievalWeapons#15]
Aether and BYG add new ores. Wouldn't it be great to have tools that we can make with them?

But there is a problem that BYG already has a battle axe. My suggestion is to add compatibility by directly copying and pasting BYG's battle axe attributes. For example, if Medieval Weapons and BYG are loaded together, BYG's recipe can be disabled!

Have a nice day, i LOVE your mods :)

**Comment by Globox1997** [comment]
Added BYG compat with [https://github.com/Globox1997/MedievalWeapons/commit/c161bca0ec7ad3904380e0c90a3262b6ed4d1757](https://github.com/Globox1997/MedievalWeapons/commit/c161bca0ec7ad3904380e0c90a3262b6ed4d1757)
Aether mod adds 5 different tool materials which takes quite a lot of time to do...
[https://github.com/devs-immortal/Paradise-Lost/blob/1.18.2/src/main/java/net/id/aether/items/tools/AetherToolMaterials.java](https://github.com/devs-immortal/Paradise-Lost/blob/1.18.2/src/main/java/net/id/aether/items/tools/AetherToolMaterials.java)

**Comment by Globox1997** [comment]
Added aether compat but for 1.19.2
