### ISSUE TITLE
Issue with Charm

### ISSUE THREAD

**Issue by ElementalIdiot** [Globox1997/MedievalWeapons#16]
For some reason when charm is installed it removes the ability to craft the weapons from this mod and I have no idea why.

**Comment by Globox1997** [comment]
looks like charm injects into the recipe manager to early [https://github.com/svenhjol/Charm/blob/master/src/main/java/svenhjol/charm/mixin/core/SortRecipesMixin.java](https://github.com/svenhjol/Charm/blob/master/src/main/java/svenhjol/charm/mixin/core/SortRecipesMixin.java) (cause as far as I know the mixins get applied in the order of the mod list which goes from a to z) and recipes from this mod won't get added to the charm recipe list.
Should be an easy fix to set the charms recipemanager mixins priority lower

**Comment by Yantsuo** [comment]
I too am facing this issue, however I have close to 0 experience in Java. Is there an easier way to fix this issue? Really love both mods, and don't want to remove either from the server.  I checked other weapon mods to see if it their recipes also got gobbled up and turns out they didn't.

**Comment by Yantsuo** [comment]
PS. ignore that "close to 0" can't even start to edit a mod, for I don't know how. pls help me i'm stoopid

**Comment by Globox1997** [comment]
Looks like the charm dev changed the redirect mixin to a normal inject which should make it compatible now, don't know if he released something yet [https://github.com/svenhjol/Charm/blob/master/src/main/java/svenhjol/charm/mixin/helper/AddSortingRecipeManagerMixin.java](https://github.com/svenhjol/Charm/blob/master/src/main/java/svenhjol/charm/mixin/helper/AddSortingRecipeManagerMixin.java)

**Comment by Globox1997** [comment]
Should be fixed with a later version of charm, reopen if still persistent.
