### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by TheNimbleNinja** [Globox1997/MedievalWeapons#17]
https://gist.github.com/TheNimbleNinja/8726b84179d501319cfe5d38d5a1c37f

**Comment by Globox1997** [comment]
Looks like in 1.17 reach entity attributes (a lib I'm using) got trouble with another mod called LotTweaks. LotTweaks is also ARR

**Comment by TheNimbleNinja** [comment]
can you fix it :)

**Comment by Globox1997** [comment]
It's not in my hands.
In the current top comment, someone is requesting if the LotTweaks dev would use the same lib, then it would be compatible :)

**Comment by Globox1997** [comment]
Maybe LotTweaks fixed the incompatibility with reach entity attributes, reopen if still persistent.
