### ISSUE TITLE
(1.17) Server crashes on startup

### ISSUE THREAD

**Issue by Moosewing** [Globox1997/MedievalWeapons#18]
https://gist.github.com/Moosewing/71097c2917f5e331fe89ec7e12f6abdc

Tested with no other mods installed besides Fabric API and MedievalWeapons. Client launches without issues but server crashes on startup. 
Deleting the "MinecraftClientMixin" line from medievalweapons.mixins.json in the server's medievalweapons-1.1.5.jar works as a temporary stop-gap solution.

**Comment by Globox1997** [comment]
Don't know how this happened but I made a mistake there xD
Should be an easy fix

**Comment by Globox1997** [comment]
[medievalweapons-1.1.6.zip](https://github.com/Globox1997/MedievalWeapons/files/6680316/medievalweapons-1.1.6.zip)
Please test this (you have to unzip the file)

**Comment by Moosewing** [comment]
Seems like that fixed it. Thanks!
