### ISSUE TITLE
Compatibility for Ranger's Haven mod

### ISSUE THREAD

**Issue by Jetspeedzz** [Globox1997/MedievalWeapons#19]
I would love to have this mod compatible with Flytre7's Ranger's Haven mod. Enchantments from the mod don't work with the bows from MedievalWeapons. Compat problem seems to be coming from your end, bows are coded differently. If possible, compatibility between the two will surely be appreciated! 

Here's a link to the mod: https://www.curseforge.com/minecraft/mc-mods/rangers-haven
Thank you!

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/MedievalWeapons/commit/fcd2c30f899c0e20001c70020a23f997e94f1741](https://github.com/Globox1997/MedievalWeapons/commit/fcd2c30f899c0e20001c70020a23f997e94f1741)
