### ISSUE TITLE
Crash upon starting

### ISSUE THREAD

**Issue by MiggiOshi** [Globox1997/MedievalWeapons#20]
Whenever I try to start up Minecraft with the medieval weapons mod, it always crashes giving me this error:

Could not find required mod: medievalweapons requires {fabric @ [*]}

Please help

**Comment by Globox1997** [comment]
This basically means you need fabric api [https://www.curseforge.com/minecraft/mc-mods/fabric-api](https://www.curseforge.com/minecraft/mc-mods/fabric-api) but if you check the relations tab on curseforge for the medieval weapons mod you will see it also needs cloth config api [https://www.curseforge.com/minecraft/mc-mods/cloth-config](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
