### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Oqkrin** [Globox1997/MedievalWeapons#21]
server crash in 1.17
[crash report](https://pastebin.com/raw/iU0cXU16)

**Comment by Billy3-00** [comment]
Same here, have no clue how to fix it as well, for some reason, it only does this in a server, when I launch it in my client, it works fine.

Any Help?

**Comment by OfficialLahusa** [comment]
I have this issue too, running medieval weapons 1.1.5 on a Fabric 1.17 server. Clientside only it works perfectly.

**Comment by OfficialLahusa** [comment]
I fixed it myself by rebuilding it from source. [Here](https://www.mediafire.com/file/hfzxl3p75lf9y7l/medievalweapons-1.1.5.jar/file) is the link for anyone having the same issue. Use this jar ONLY on the server, you need to use the version downloaded from CurseForge on the client. Thank me later ^^

**Comment by Globox1997** [comment]
Fixed it some time ago but haven't released a version, will do it today :) [https://github.com/Globox1997/MedievalWeapons/commit/56d34107f47bebf6b9431913391ee43e0b248c71](https://github.com/Globox1997/MedievalWeapons/commit/56d34107f47bebf6b9431913391ee43e0b248c71)
