### ISSUE TITLE
Incompatibility with Inventorio

### ISSUE THREAD

**Issue by JumperCzech** [Globox1997/MedievalWeapons#22]
https://www.curseforge.com/minecraft/mc-mods/inventorio
Having an item in offhand and a weapon that can block in main hand causes the player to be unable to attack, use the offhand item and block with the weapon. (Which are different buttons with Inventorio.)

https://github.com/Lizard-Of-Oz/Inventorio/issues/60

**Comment by Globox1997** [comment]
does this happen with every weapon while both mods are installed or only with specific ones?

**Comment by JumperCzech** [comment]
> does this happen with every weapon while both mods are installed or only with specific ones?

only weapons that have the ability to block, as the op says

**Comment by Globox1997** [comment]
weapons from the mod which can block are double handed weapons which means you can't use them when you have items in both hands

**Comment by Globox1997** [comment]
But I'm not sure if I understand you correctly

**Comment by JumperCzech** [comment]
> weapons from the mod which can block are double handed weapons which means you can't use them when you have items in both hands
ok so only half of the og issue is a bug ig
with inventorio, using the right click functionality of your main hand item and the right click functionality of the offhand item are two separate buttons. I think you are still supposed to be able to use the offhand item, right? Which you can't.

also, it would be nice if the game told you that you can't use the weapons with item in offhand if you try to, since it just looks like a bug with no animations or nothing.

**Comment by Globox1997** [comment]
I added a tooltip for those items to make clear it can't get used when both hands hold items :)
it is intentional that you can't use either item when one of them is a double handed item
