### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by TheNimbleNinja** [Globox1997/MedievalWeapons#25]
https://gist.github.com/TheNimbleNinja/4c8ef3efb7556950687d32d0cfe83a84

**Comment by Globox1997** [comment]
Please update to the latest mod version [https://www.curseforge.com/minecraft/mc-mods/medievalweapons/files/3393652](https://www.curseforge.com/minecraft/mc-mods/medievalweapons/files/3393652)
