### ISSUE TITLE
Longbow is uncraftable in 1.17.1.

### ISSUE THREAD

**Issue by Art1xs** [Globox1997/MedievalWeapons#29]
I believe this is because polymorph is not out for 1.17 yet, however, I could just be missing something because I can craft the recurve bow but not the longbow. Thank you!

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/acf4565a7bcedc7a657db79b0a225f36a4e96923](https://github.com/Globox1997/MedievalWeapons/commit/acf4565a7bcedc7a657db79b0a225f36a4e96923)
