### ISSUE TITLE
Dagger stealth attack reports more damage than is actually done

### ISSUE THREAD

**Issue by FewerFlaws** [Globox1997/MedievalWeapons#3]
I use ToroHealth Damage Indicators to see damage done and current health on mobs.  On stealth attacks wooden daggers report 5 damage but reduce mob HP by 4 health.  Diamond daggers report 8 damage but reduce mob HP by 7.

**Comment by FewerFlaws** [comment]
This was tested on cows, sheep, spiders, and zombies.  The armor on zombies reduced both the reported damage and actual damage (so the problem still existed).

**Comment by Globox1997** [comment]
I checked it and realized the damage indicator you are using can't show comma numbers and the damage gets increased by 1.5 :)
In the next update I increase the number to 2.0

**Comment by FewerFlaws** [comment]
Ohh, gotcha.  Thank you very much for looking into this =D
