### ISSUE TITLE
additional additions support

### ISSUE THREAD

**Issue by Lukebb04** [Globox1997/MedievalWeapons#30]
add support for the [additional additions](https://www.curseforge.com/minecraft/mc-mods/additional-additions) mod

**Comment by Globox1997** [comment]
Does this mod add weapons from the materials it is adding?

**Comment by Lukebb04** [comment]
yes

**Comment by chrsrns** [comment]
Bumping this. I'm trying to add the support on a temporary fork. But so far, I only have the Rose Gold model assets done.

About the models for the additional additions support, I'd like to know how the assets in `src/main/resources/assets/medievalweapons/textures/entity` are generated?

**Comment by Globox1997** [comment]
Since the visual bigger models are entities these assets are for the models here: [https://github.com/Globox1997/MedievalWeapons/tree/1.18/src/main/java/net/medievalweapons/entity/model](https://github.com/Globox1997/MedievalWeapons/tree/1.18/src/main/java/net/medievalweapons/entity/model)

**Comment by chrsrns** [comment]
What is your flow for creating the assets from `src/main/resources/assets/medievalweapons/textures/entity`? My current flow is taking the existing ones as templates and recoloring them, which is what I did for [these assets](https://github.com/Globox1997/MedievalWeapons/files/7657832/rose_gold_items.zip). 

I've already added some entries in the following files: 
- `src/main/resources/assets/medievalweapons/lang/en_us.json`
- `src/main/resources/data/tooltiprareness/tags/items/uncommon_item.json`
- `src/main/resources/data/medievalweapons/advancements/medieval_rose_gold_recipes.json` (New file for, I'm guessing advancements)
- `src/main/resources/assets/medievalweapons/models/item` (Added some JSON files) (Other than changing the texture.layer0 values, the added files are copies of the existing `golden_*.json` files.)

Is that all that I should change when adding new items? Other than creating new entity models to `src/main/resources/assets/medievalweapons/textures/entity`, I'm guessing I also need to add recipes, which I'll try to figure out later how to.

I noticed that Blockbench was used at some point, based on [Line 2 from this file](https://github.com/Globox1997/MedievalWeapons/blob/1.18/src/main/resources/assets/medievalweapons/models/item/golden_small_axe.json). Do you still have the project files somewhere? It'll make it easier to make the new assets on `src/main/resources/assets/medievalweapons/textures/entity`.

**Comment by Globox1997** [comment]
That is what I basically do :D 
yea I should have them anyhwere, contact me on discord, Globox_Z #1024

**Comment by chrsrns** [comment]
Alright. I sent a friend request.

**Comment by RatDonkeyGoat** [comment]
they changed the way rose gold works in additional additions here is the compat file with the new recipies

**Comment by RatDonkeyGoat** [comment]
[CompatRecipes.java.zip](https://github.com/Globox1997/MedievalWeapons/files/10510837/CompatRecipes.java.zip)
[CompatRecipes.class.zip](https://github.com/Globox1997/MedievalWeapons/files/10510838/CompatRecipes.class.zip)
[medievalweapons-1.4.2.jar With Additional Additions corrected recipe.zip](https://github.com/Globox1997/MedievalWeapons/files/10510839/medievalweapons-1.4.2.jar.With.Additional.Additions.corrected.recipe.zip)

**Comment by Globox1997** [comment]
Updated additional additions compat with [https://github.com/Globox1997/MedievalWeapons/commit/567db46c88827bfa8f0286eeddc116799e1e9ba4](https://github.com/Globox1997/MedievalWeapons/commit/567db46c88827bfa8f0286eeddc116799e1e9ba4)
Thank you @RatDonkeyGoat
