### ISSUE TITLE
Compat: Sihytcamc

### ISSUE THREAD

**Issue by AzureMonument** [Globox1997/MedievalWeapons#32]
Sihytcamc (So I heard you talking crap about minecraft combat) adds the ability to edit the statistics of weapons to become inline with the additions of the combat snapshot- but adding the weapons from this mod to the config fail to to be properly affected by it. Other mods like sentimentality, additional additions, and harvest scythes do work- so I have some confidence it's not Sihytcamc.

Here's the config I am using (in the tools json):
[sihywtcamc.zip](https://github.com/Globox1997/MedievalWeapons/files/7027652/sihywtcamc.zip)

**Comment by Globox1997** [comment]
Maybe it will be fixed with the coming update but that is not guaranteed

**Comment by Globox1997** [comment]
Reopen if this incompatibility is persistent.
