### ISSUE TITLE
Crash when rendering a player that is using a medieval weapon

### ISSUE THREAD

**Issue by UltimateCoffee** [Globox1997/MedievalWeapons#33]
Client crashes anytime it tries to render a player with a medieval weapon. Even if I hit F5 to view myself while holding one.

https://pastebin.com/0V0912mM

**Comment by UltimateCoffee** [comment]
All the unique weapons are actually what's causing the issue. longsword, dagger, recurve bow, and long bow work fine, all other weapons cause the client rendering them to crash (3rd person view only).

**Comment by Globox1997** [comment]
Looks like it is incompatible with the mod called BannerCapeFeatureRenderer

**Comment by UltimateCoffee** [comment]
I appreciate the response.
I just tested on a new server, with only MedievalWeapons and the mod MoreBannerFeatures, which has the BannerCapeFeatureRenderer. With only these mods, everything works fine.
Additionally, I got the crash again, and a new crash report. This one doesn't mention the BannerCapeFeatureRenderer.
Can you advise please?

https://pastebin.com/HPws45eM

**Comment by UltimateCoffee** [comment]
Found the issue. There is an incompatibility with the Pehkui mod.
Is it possible for you to fix this?
If Pehkui and MedievalWeapons are installed, when you see a 3rd person model in the world holding one of the problem weapons: Healing Staff, Mace, Waraxe, Javeline, Lance: the client crashes.

**Comment by Globox1997** [comment]
do you use the latest mod version?

**Comment by UltimateCoffee** [comment]
Yes,
MedievalWeapons 1.1.6
Fabric API 0.39.2
Fabric 0.11.6
Pehkui 2.3.0

**Comment by Globox1997** [comment]
mh, it should have been fixed with this [https://github.com/Globox1997/MedievalWeapons/pull/31](https://github.com/Globox1997/MedievalWeapons/pull/31)
Wondering why it doesn't work

**Comment by UltimateCoffee** [comment]
Not sure. Just downloaded the latest of this mod, its dependencies, and pehkui. Tested using only these newly downloaded mods on a clean minecraft fabric install and got the same crash.

https://pastebin.com/X5Rf8tht

**Comment by UltimateCoffee** [comment]
It looks like this commit was made on Aug 22, 2021
The latest release of the mod was on July 19, 2021

Is it possible this code change isn't in the released version of the mod, that I am downloading?

**Comment by UltimateCoffee** [comment]
Rebuilt the mod from github.
The rebuilt mod is working.

**Comment by Globox1997** [comment]
oh xD than I forgot to release an update

**Comment by UltimateCoffee** [comment]
Thanks for the help!
