### ISSUE TITLE
Better BetterEnd Textures

### ISSUE THREAD

**Issue by NerVeZs** [Globox1997/MedievalWeapons#36]
The textures for the better end Aeternium medieval weapons really just look like iron, I am asking if you could change it to look more like a darker blueish grey like how Aeternuim looks.

**Comment by Globox1997** [comment]
If you are a texture artist, I'm open for these mentioned textures :)

**Comment by NerVeZs** [comment]
What website/app could I use to do textures, I bet I could whip up
something up.

**Comment by Globox1997** [comment]
mh any software which can edit png files^^
I usually use paint.net

**Comment by NerVeZs** [comment]
Could you send me png’s of all the Aeternium Medival weapons?

**Comment by Globox1997** [comment]
You can find them here :) [https://github.com/Globox1997/MedievalWeapons/tree/master/src/main/resources/assets/medievalweapons/textures/item](https://github.com/Globox1997/MedievalWeapons/tree/master/src/main/resources/assets/medievalweapons/textures/item)
Don't forget the entities here: [https://github.com/Globox1997/MedievalWeapons/tree/master/src/main/resources/assets/medievalweapons/textures/entity](https://github.com/Globox1997/MedievalWeapons/tree/master/src/main/resources/assets/medievalweapons/textures/entity)

**Comment by Globox1997** [comment]
Reopen if you still want to tweak the textures.
