### ISSUE TITLE
Attack Range Issues, Loyalty, Suggestions

### ISSUE THREAD

**Issue by BlasterAdreis** [Globox1997/MedievalWeapons#39]
Was checking out the mod and noticed that the weapons with reduced attack range were still hitting from the same max range as the standard sword (tested Dagger and Mace). Didn't think to check if the ones with longer range were working or not, but might be good to check both. 

Also found that even though the javelin could use loyalty, the throwing axe couldn't. Wasn't sure if that was by design. 

I love the mod but had a few ideas that I thought I would pass on. I feel like the dagger is too strong- even without sneak attack, it out DPS's the basic sword and every other weapon in the mod (12.8 on the sword to 14 on the dagger). I will admit I don't know what its like using it with -1 attack range as per above, but I do feel that it needs to deal less damage. 

Also I would love a config file for the mod. It would be nice to be able to turn off certain enchantments on a weapon if it fits someones fancy, or just disable a weapon if need be (I would turn off dagger on my server as it might be op with the rogue class from another mod). I'm not a coder so I'm unsure on the difficulty on making such a thing, but I hope its possible. 

Overall love the mod and hope you keep updating it!

**Comment by JettJ377** [comment]
Yeah I noticed That issue too

**Comment by Globox1997** [comment]
Fixed reach bug with [https://github.com/Globox1997/MedievalWeapons/commit/c5118089f86610b5713cb5f70015d27516cf64b3](https://github.com/Globox1997/MedievalWeapons/commit/c5118089f86610b5713cb5f70015d27516cf64b3)
And franciscas can intentionally not get enchanted with loyality.
Your ideas are good :)

**Comment by Globox1997** [comment]
Pls open a new issue with your suggestions for better clarity since the main bug was fixed
