### ISSUE TITLE
Sneak attack damage from the dagger is unreliable.

### ISSUE THREAD

**Issue by FewerFlaws** [Globox1997/MedievalWeapons#4]
While troubleshooting an issue with a health bar + damage indicator mod I did some data gathering.  After drinking a potion of invisibility I whacked a 220HP skeleton with a wooden dagger until it died.  The negative numbers in the following list are damage reports.  I believe the -5 numbers are successful sneak attacks which properly did 4.5 damage (the damage indicator erroneously rounded up).  The -3 numbers seem to be sneak attack failures that actually dealt 3 damage.
  * 220
  * (-5) 216
  * (-5) 211
  * (-5) 207
  * (-3) 204
  * (-5) 199
  * (-3) 196
  * (-3) 193
  * (-5) 189
  * (-3) 186
  * (-5) 181
  * (-5) 177
  * (-3) 174
  * (-5) 169
  * (-3) 166
  * (-3) 163
  * (-5) 159
  * (-5) 154
  * (-3) 151
  * (-3) 148
  * (-5) 144
  * (-3) 141
  * (-3) 138
  * (-3) 135
  * (-3) 132
  * (-5) 127
  * (-5) 123
  * (-3) 120
  * (-3) 117
  * (-5) 112
  * (-3) 109
  * (-5) 105
  * (-3) 102
  * (-5) 97
  * (-5) 93
  * (-3) 90
  * (-5) 85
  * (-5) 81
  * (-3) 78
  * (-3) 75
  * (-3) 72
  * (-3) 69
  * (-5) 64
  * (-5) 60
  * (-3) 57
  * (-5) 52
  * (-3) 49
  * (-3) 46
  * (-5) 42
  * (-5) 37
  * (-5) 33
  * (-3) 30
  * (-5) 25
  * (-5) 21
  * (-5) 16
  * (-3) 13
  * (-5) 9
  * (-5) 4
  * (-4) Dead
If you sum the damage reports you get 235, which exceeds the skeleton's HP by 15.  There were exactly 30 reports of (-5), so the accumulated rounding error accounts for this excess.  That's why I believe the (-3) damage attacks were failures to sneak attack.  There were 27 of those.  The killing blow appears to be a sneak attack, so it's roughly a 53% success rate in this trial.  I did not sneak at all; I only used an invis potion.

I'm not sure if this is intended or not, but I thought I should let you know since I had all the data anyway =P

**Comment by Globox1997** [comment]
Thanks for the report, already fixed this bug a few days ago ;) next update it should work fine

**Comment by Globox1997** [comment]
Fixed it in the newest update
