### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by VaIerka** [Globox1997/MedievalWeapons#41]
Some mods adds unique weapons that dropped from bosses etc and they usually act like regular sword.
Would be nice to have a config option to set a certain behavior to a certain fighting style. (like if the sword is very big, I want Steve to hold it with both hands)

Very nice mod btw =)

**Comment by Globox1997** [comment]
You can create a datapack and add those weapons to the double_handed_items or across_double_handed_items tag :)
