### ISSUE TITLE
craft recipes

### ISSUE THREAD

**Issue by BBlazeOfficial** [Globox1997/MedievalWeapons#42]
hi i am new and i love this mod but what are the recipes?

**Comment by Globox1997** [comment]
I recommend to use [https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) to get the recipes

**Comment by BBlazeOfficial** [comment]
okai thx i just did not know so i used the crafting book to look up but thx for the mod though
