### ISSUE TITLE
Unable to use Diamond Longsword

### ISSUE THREAD

**Issue by Severnarch** [Globox1997/MedievalWeapons#43]
I'm playing on a multiplayer server with origins and stuff, I crafted two Diamond Longswords but they don't work.
I'm on 1.17.1

**Comment by Globox1997** [comment]
What do you mean by "they don't work" exactly? you can't hit entities with them?

**Comment by Severnarch** [comment]
Yeah, I'm unable to hit entities with them, single-wield or dual-wield.

**Comment by KubanczykT** [comment]
If you can't even swing the sword, it's probably because you have something in the other hand(shield, totem, etc.), if it still doesn't work, well, I can't help you

**Comment by Globox1997** [comment]
My guess is, as KubanczkT said, you had another item in your other hand while trying to use such big weapon. Reopen if that is not the case
