### ISSUE TITLE
War Axe sweeping does up to 3x the damage

### ISSUE THREAD

**Issue by Xano11** [Globox1997/MedievalWeapons#44]
I do not know its a bug or a hidden feature, but, the War axe can do up to 3x times the damage of the source attack. That is with or without Sweeping Edge.

Example : If you have 2 iron golems next to each other, the one being directly attacked will take less damage and the one being hit by the sweeping will die in less hits.

**Comment by Globox1997** [comment]
3x times sounds a little crazy but yea the war axe has sweeping damage by nature

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/a501d5b4a8ac28f1099b499cc4191d926a2a0572](https://github.com/Globox1997/MedievalWeapons/commit/a501d5b4a8ac28f1099b499cc4191d926a2a0572)
