### ISSUE TITLE
Copper Compatibility

### ISSUE THREAD

**Issue by victor578v** [Globox1997/MedievalWeapons#45]
Compatibility to mods that add Copper tools such as Copper armor and tools (1.18)

**Comment by Pirogiran** [comment]
It would be nice if there was compatibility with [Copper Equipment mod](https://www.curseforge.com/minecraft/mc-mods/copper-equipment-fabric) (since it uses compressed copper)

**Comment by Globox1997** [comment]
If someone creates the assets for medieval weapons I might make it compatible with it

**Comment by Globox1997** [comment]
Reopen if still someone wants the compat with the copper mod. Please provide the textures then.
