### ISSUE TITLE
Range Modifiers Do Not Work

### ISSUE THREAD

**Issue by catanobro10** [Globox1997/MedievalWeapons#46]
After doing some light testing, I noticed that all of the range modifiers for the weapons do not work as intended. However, I dug into the source code and figured out why and it's weird. As best as I can tell, the game does two checks to decide on the reach of an item: it first does a "before" check, then a "during" check for the attack. The "before" check is what tells the attack indicator to show that the creature is in range, and is necessary for the "during" check, which then makes sure the creature is in range before dealing damage. The code for the weapons is missing the "before" check, which uses the REACH modifier. So the two lines of code that increase/decrease the range of a weapon are:

`builder.put(ReachEntityAttributes.REACH, new EntityAttributeModifier("Attack range", 0.8D, EntityAttributeModifier.Operation.ADDITION));

builder.put(ReachEntityAttributes.ATTACK_RANGE, new EntityAttributeModifier("Attack range", 0.8D, EntityAttributeModifier.Operation.ADDITION));`

Hopefully that makes sense.

**Comment by JettJ377** [comment]
Hopefully the development team sees this

**Comment by Globox1997** [comment]
Thanks for reporting and giving the fix solution :)
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/c5118089f86610b5713cb5f70015d27516cf64b3](https://github.com/Globox1997/MedievalWeapons/commit/c5118089f86610b5713cb5f70015d27516cf64b3)
