### ISSUE TITLE
Weapon Damage

### ISSUE THREAD

**Issue by MisterrBrown** [Globox1997/MedievalWeapons#49]
it would be nice if we could modify the damage value of the weapons in the config menu ! I want the javelin to be stronger than the trident !

**Comment by Xano11** [comment]
To add to their request : Modifying Damage, Range, Sweeping Damage and Attack speed would be very appreciated !

**Comment by Globox1997** [comment]
No plans to make it configureable. Open for suggestions to tweak the different stats of weapons for a better balance.
