### ISSUE TITLE
Impressions, because apparently my comment is too long for curseforge :,(

### ISSUE THREAD

**Issue by AzureMonument** [Globox1997/MedievalWeapons#5]
Alright, I'm gonna give my initial impressions after playing with this a bit in a single-player survival world on hard mode, with the current stage of progress being full iron and just got diamonds (but no gear out of diamonds yet and haven't been to the nether).

Some things to note: I play with inventory hotswap and the backslot mod (adds a backslot and waist slot that can be switched to with the g-key and shift-g respectively). I also have battle towers and Yung's caves/mineshafts as well as Eldritch mobs and origins+origins classes with a datapack called 'versatile humans' which allows the human race to use two classes- of which I am using warrior (bonus damage and faster when holding shield) as well as blacksmith.

My current basic setup in the world is having a normal iron sword as my main weapon with a shield in my offhand. On my backslot I use a healing staff and on my waist I have a dagger. I've got a bow, but not a consistent source of arrows yet so I generally do not use it. As an extra weapon I've got both a longsword and a lance in my inventory that I can hotswap to from my basic sword.

When started I attempted to use the lance when not mounted- and frankly am somewhat sad with it (spears are my favorite medieval weapon). The lance is slow, and does the same damage at base as a basic iron sword, while also not having the capability to hit multiple enemies (as far as I've noticed. No idea if it can take sweeping edge, no enchantments yet). This makes it pretty much unusable in any group fight, and even in a one-on-one, due to its slow attack speed the range you gain means little, as you'd have to attack faster (and subsequently do less damage) to keep enemies away (though you can kill them before they get to you quite easily at this point, it is far slower than a basic sword). I know that the lance is supposed to be used mounted, but actually using a mount in combat in minecraft is not only rare, but rather annoying, especially with the tendency to hit your own. Frankly speaking, considering the lance seems to lack the multi-hitting capabilities of the basic iron sword, it's attack speed being equivalent to said weapon would probably be well balanced, though I don't know how that would effect mounted combat, which I need to test. Luckily there are horses nearby, but I need a saddle...

The longsword is actually the first weapon I made- though a stone one. This weapon seems incredibly balanced compared to most others I've tried, despite the fact that it removes your offhand (and subsequently your shield) from the equation, which is a massive drop in survivability as far as I'm concerned, especially when dealing with groups of skeletons in the open. Nonetheless, the longsword excels at one v one with non-ranged opponents, as well as hordes of zombies as my first naked foray into a battletower with nothing but a stone longsword can attest (I did not get particularly far. Decided to jump ship when a ghastly, fiery zombie blew open the floor above me and dropped the zombies spawning up there on my head). The range, decent attack speed, and nice damage make up for not having a shield. Haven't used it much when caving however, as the tendency to run into skeletons in narrow quarters has made having a shield pretty damn important, and due to needing to get all items out of my offhand before I'm able to use the weapon has left it sitting in my inventory. (Suggestion: Two handed weapons simply disable off-hand when held instead of becoming useless. I don't know if this is possible)

The dagger is a weapon I made originally (stone) cause I didn't want to use a slow longsword while chasing fish in a river. (I've got river redux- so big river). Outside of that I've mostly used it in the battletower near my base when going up the ladders in order to clear out any mobs that may be standing right above said ladder, in which it has performed spectacularly. The quick speed and decent damage is great for taking out single mobs (works well when close to skeletons) as well as dealing with passive critters and getting tons and tons of fish. In fact if you're jumping into water to get fish, bring a dagger to do so. Makes it so much easier...

The healing staff is something I haven't actually used much of yet. Thanks by the way for answering my stupid question on how to use it a few days ago. I've only used the stone variant, and haven't used it all that much easier (mostly because I keep bloody forgetting to do so. Too used to retreating from battle to scorf down food). It basically makes a small area where your aming that seems to slow you slightly, but also heals you for a few seconds. Don't really know how fast the healing is, I need more testing. It seems it is going to mostly be useful when needing to stand your ground in one location (like at the beginning of a battletower room) or when you retreat to a safe position (though I suppose if you are in multiplayer, the ability to pick the spot it manifests can let you be a backline). It doesn't help that it counts as a two-handed weapon from what I can tell, and as such doesn't work with anything in your offhand. Again, having the offhand be auto-disabled when a two handed weapon is held would be great. Also I don't know if it heals enemies... I should probably test that. Testing testing testing...

The Francisca... is a weapon I haven't really used due to one reason: The shaders I play with make it invisible when thrown. Which is a... mild issue. As a melee weapon it works okay, pretty much weaker all around than a basic sword. The main use is obviously as a ranged supplement, which I would love to use. Especially if later on I can attach loyalty to it, and have it return to me. Though, as I've not done any enchanting yet, I've not idea if that is possible. Without said enchantments and turning off my shaders, it's... 'meh' I supposed. The weakness of having to go collect it is pretty large, and since there really isn't any hostile enemy that runs from the player (besides maybe skeletons) it can't be used as a finisher all that much. As a fight starter it's not too great either, as the damage can easily be replaced with a single hit of any other weapon and it can only hit one target (which also makes it pretty much useless in a group fight compared to almost any other weapon). Enchantments will likely change this, as I imagine it may be possible to one-shot enemies with a fully decked netherite francisca, but until then, or until I can put loyalty on it, mostly underwhelming.

Iron Axe: A slightly slower, higher damage, single-target basic iron sword. Not much really to say about it. If you've got a tendency to go for crits at every opportunity but don't want to use a normal iron axe due to its slowness, this weapon would do that just fine. Probably better in one-on-one fights than a basic iron sword, but I prefer the sword to the axe tbh. It's not two handed, so it can be used with a shield or offhand just fine.

The big iron axe is... a disappointment. It's a two handed weapon, so you can't use any offhand with it (especially shield) It's slow. Ridiculously slow. It's damage is comparable to a longsword of the same level, with none of the range advantage. It has basic sweeping, but you can't sweep while jumping- so no critical hits that high damage weapons like the axe normally excel with. As a single target weapon it is utterly useless, outclassed by any other weapon (even the dagger), and in group fights it attacks so slowly that you may as well use any other weapon with basic multi-hitting capabilities, as your dps will be far higher. Not to mention that again, it is a two handed weapon, so you can't defend yourself while waiting for its attack timer to refresh, and since it takes too long you're screwed in any close-quarters group fight, as even if you attack while uncharged it won't do enough damage to kill them, and you can't use its sweep. Overall a really poorly balanced weapon that I can't recommend using at all. Maybe if it's attack speed was something like the lances current attack speed (0.8 instead of 0.6), along with a small increase in damage (from the current 8 to 9) it may become worthy. Even adding some extra knock-back may be a nice touch. One word of disclaimer hear, is that again, I don't have enchantments. I've no idea how this weapon would handle with something like sweeping edge III tacked on, but considering that every other weapon outperforms it... Well. My hopes aren't too high.

I have not used any of the bows yet in my survival world (my current bow was a drop from a skeleton). I'll come back and edit this comment or add a new one when I do.

Overall, a nice set of weapons. Would be nice to have some extra diversity (like maces), but I haven't really watched the songs of war series so don't really know the aesthetic. (I'm assuming maces would be fine).

Anyway. Thanks for the mod~♫

**Comment by AzureMonument** [comment]
I hope you can still see this if I close it. And sorry for posting this here, curseforge just marked it as spam so I don't know if you'll see it over there at all.

**Comment by Globox1997** [comment]
This text could be a novel xD Really nice and thank you for this feedback, appreciate it a lot.
First of all I want to describe shortly the idea behind this mod (and probably for almost all of my mods). 

The goal is to have some base mods for a rpg style modpack with classes and a progression system.
For example at the beginning you can decide which class you wanna play like a warrior, priest or archer and each of them have their own abilities + limit factors. Warrior can't use the priest staff, priest can't use melee weapons  and so on.

On this point of view, you would have too many different types of weapons which you actually shouldn't be able to but I mean that's up to the player.

All weapons should be balanced of course so I need exactly such a feedback to improve those settings.
Mounted combat is especially on servers not so easy but that's why the lance is in the mod :) I like the idea of some kind of piercing attack cause the multiple hit is debuffed. 

For double handed weapons there is a config option to automatically clear your offhand when double handed is used.
Sad to hear that the renderer doesn't work cause its just a normal entity in the world.
I think I answered your question about the healing staff in another issue but it damages some other mobs :)

The big axes have basic sweeping which makes it powerful when used against more than one mob so imo it's pretty strong.
There could be somekind of 40% of damage reducing when trying to defend with the big axe or basic knockback sounds also good.

 We can talk about some tweaks for specific weapons in the future of course ;)

**Comment by Globox1997** [comment]
Please add me on discord to elaborate about the mod Globox_Z #1024
