### ISSUE TITLE
Unavailable message. (death.attack.javelin)

### ISSUE THREAD

**Issue by Techbites457** [Globox1997/MedievalWeapons#50]
Hello! This is a minor issue, but there doesn’t seem to be a death message for the thrown weapons. Both the javelin and the francisca display death.attack.NAME as the death message.

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/MedievalWeapons/commit/c5118089f86610b5713cb5f70015d27516cf64b3](https://github.com/Globox1997/MedievalWeapons/commit/c5118089f86610b5713cb5f70015d27516cf64b3)
