### ISSUE TITLE
Suggestion: double sided spear/glaive

### ISSUE THREAD

**Issue by KubanczykT** [Globox1997/MedievalWeapons#52]
Youtube video with such weapon (the only I could find): https://www.youtube.com/watch?v=AnnKn1YJtCA

A double handed weapon, that would have lower damage and reach than other weapons, but the sweeping would be essentially 360 degrees. It could have really low dmg, pretty fast attack speed, but sweeping would hit everything in a close proximity to you. It could also be something that you could hold a button, and it would at first start attacking slowly, but then slowly speed up to a certain point. It would be usful aganist swarms of enemies from all sides

**Comment by Globox1997** [comment]
Lately no intention for adding new weapons to this mod.
However I will probably only add weapons from the series Songs of War to this mod.
