### ISSUE TITLE
[Server] INFO Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData

### ISSUE THREAD

**Issue by Jlenzer** [Globox1997/MedievalWeapons#53]
Running on shockbyte.  Other mods:
cloth-api-2.0.54.jar
cloth-config-5.0.38-forge-1.17.jar
fabric-api-0.45.2+1.17.jar
medievalweapons-1.1.7.jar

Loads up fine, but throws stack below when adding medievalweapons

09.01 03:22:21 [Server] main/FATAL Failed to start the minecraft server
09.01 03:22:21 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'medievalweapons'!
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.minecraft.server.Main.main(Main.java:97) [server-intermediary.jar:?]
09.01 03:22:21 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
09.01 03:22:21 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
09.01 03:22:21 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
09.01 03:22:21 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
09.01 03:22:21 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
09.01 03:22:21 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
09.01 03:22:21 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
09.01 03:22:21 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
09.01 03:22:21 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
09.01 03:22:21 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
09.01 03:22:21 [Server] INFO at net.medievalweapons.init.ConfigInit.<clinit>(ConfigInit.java:8) ~[medievalweapons-1.1.7.jar:?]
09.01 03:22:21 [Server] INFO at net.medievalweapons.MedievalMain.onInitialize(MedievalMain.java:24) ~[medievalweapons-1.1.7.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO ... 15 more
09.01 03:22:21 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
09.01 03:22:21 [Server] INFO at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
09.01 03:22:21 [Server] INFO at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
09.01 03:22:21 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
09.01 03:22:21 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
09.01 03:22:21 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
09.01 03:22:21 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
09.01 03:22:21 [Server] INFO at net.medievalweapons.init.ConfigInit.<clinit>(ConfigInit.java:8) ~[medievalweapons-1.1.7.jar:?]
09.01 03:22:21 [Server] INFO at net.medievalweapons.MedievalMain.onInitialize(MedievalMain.java:24) ~[medievalweapons-1.1.7.jar:?]
09.01 03:22:21 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
09.01 03:22:21 [Server] INFO ... 15 more

**Comment by Globox1997** [comment]
cloth-config-5.0.38-forge-1.17.jar
you will need the fabric version of cloth config :)

**Comment by Jlenzer** [comment]
duh . . . Thank You!!
