### ISSUE TITLE
Better end pedestals do not work with two-handed weapons

### ISSUE THREAD

**Issue by sw-github** [Globox1997/MedievalWeapons#54]
Better end pedestals do not work with two-handed weapons.
Example: when I right click a pedestal from the better end mod with a two-handed weapon like a longsword, the weapons does not float on top of the pedestal. However, when i right click it with a one-handed weapon such as a dagger, the pedestal works like normal.

**Comment by Globox1997** [comment]
It works at least in the latest version but I found another bug
![2022-05-20_10 39 26](https://user-images.githubusercontent.com/55102939/169489606-6c7b0237-e115-447a-80b1-e1bbc3cd8525.png)
