### ISSUE TITLE
Attack Range Modifiers Don't Do Anything

### ISSUE THREAD

**Issue by JettJ377** [Globox1997/MedievalWeapons#55]
I tested weapons that supposedly had higher/lower attack range, meaning they can attack from farther away/can only attack close by, but when I tested to see if they actually had different attack ranges, they seemed to all have the exact same attack range despite the supposed modifier.

I'll link a different issue that shows a way to fix this
[https://github.com/Globox1997/MedievalWeapons/issues/46](url)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/c5118089f86610b5713cb5f70015d27516cf64b3](https://github.com/Globox1997/MedievalWeapons/commit/c5118089f86610b5713cb5f70015d27516cf64b3)
