### ISSUE TITLE
Healing staffs no longer heal at all?

### ISSUE THREAD

**Issue by AzureMonument** [Globox1997/MedievalWeapons#6]
So I recently updated to the latest release (1.0.7), and I noticed healing staffs were debuffed. When I attempted to heal, I received nothing? Even standing in the aura did not give me any extra health outside of basic regen, and when my regen was up I repeated it several times and it failed to even heal half a heart.

I am playing hard mode, and am in the nether at the moment.

**Comment by Globox1997** [comment]
Healing staff is mainly for support not for self healing :) the aura will only heal other players but if you hold long enough right click, you should gain a little bit of health
