### ISSUE TITLE
Conflict with Fabric Shield Lib | 1.18.1

### ISSUE THREAD

**Issue by ghost** [Globox1997/MedievalWeapons#60]
Mods used:
Medieval Weapons v1.1.7
Cloth Config API (Fabric) v6.1.48
Fabric API v0.46.2
Fabric Shield Lib v1.4.5

Issue: With Fabric Shield Lib installed alongside your mod, shields do not block melee attacks. There's a few shield mods that rely on FSL in order to load and function, which means people have to make a choice of whether to use your mod or the shield mods that rely on FSL.

Replication:
1. Make a profile with the mods listed above, no need for other shield mods that use FSL but you can add them if you wish to see that it affects those too.
2. Grab a vanilla shield and a zombie
3. Let the zombie attack you while in survival and watch your health get hit despite blocking (shield loses durability to show it was used)

Notes: Not sure who's mod is the one breaking the other, but since the mods that depend on FSL worked after removing your mod, I though I'd post it here first. If needed, I can post it on their GitHub too.

**Comment by celophys** [comment]
Yes i have the same bug

**Comment by rikka0w0** [comment]
I think something is wrong with this:
https://github.com/Globox1997/MedievalWeapons/blob/cabfaa96cd0b7ae56c7c619320e238d6b31309f6/src/main/java/net/medievalweapons/mixin/PlayerEntityMixin.java#L44-L50

**Comment by celophys** [comment]
https://user-images.githubusercontent.com/84269120/152639716-f1833eaa-2840-444b-ae06-41da01ef380a.mp4

A video of the issue

**Comment by rikka0w0** [comment]
https://github.com/Globox1997/MedievalWeapons/blob/cabfaa96cd0b7ae56c7c619320e238d6b31309f6/src/main/java/net/medievalweapons/mixin/PlayerEntityMixin.java#L44-L50
Line 44 is causing the problem, it breaks every other shields, not just those added with shield api. Removing this mixin fixes the problem. Im not too sure what this mixin intended for.

**Comment by celophys** [comment]
rikka0w0 there is a way to me to fix it for my modpack?

**Comment by Globox1997** [comment]
It is used to balance shields :)
I fixed it with [https://github.com/Globox1997/MedievalWeapons/commit/c0c69e062cb1813190bdea1e4d007a86374a11c7](https://github.com/Globox1997/MedievalWeapons/commit/c0c69e062cb1813190bdea1e4d007a86374a11c7) and it can be disabled by setting the cooldown to 0 ticks

**Comment by celophys** [comment]
Thanks!!!!
