### ISSUE TITLE
Ticking entity crash with bugged Aeternium Franscisca

### ISSUE THREAD

**Issue by Skeithh** [Globox1997/MedievalWeapons#61]
How it occurred:

Version of the mod:
medievalweapons-1.1.7

1. Threw Franscisca at block
2. Teleported out of chunk
3. Returned to chunk (via teleport)
4. Franscisca was unable to be picked up by any player, including weapon owner
5. Player attempted to go below the weapon, and  broke the block it was laying on
6. Weapon hit player, crashed the server

Attached the crash log here

[crash-2022-02-19_13.32.29-server.txt](https://github.com/Globox1997/MedievalWeapons/files/8102190/crash-2022-02-19_13.32.29-server.txt)

**Comment by Globox1997** [comment]
Does this happen in mc version 1.18.2 too?
and does this happen with an iron francisca too?

**Comment by Globox1997** [comment]
Reopen if still persistent and keep in mind that I only work on the latest version of my mods cause of time reasons.
