### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'medievalweapons'!

### ISSUE THREAD

**Issue by kittech0** [Globox1997/MedievalWeapons#63]
Error: [crash-2022-03-08_20.49.38-server.txt](https://github.com/Globox1997/MedievalWeapons/files/8209234/crash-2022-03-08_20.49.38-server.txt)
Logs: [latest.log](https://github.com/Globox1997/MedievalWeapons/files/8209237/latest.log)

**Comment by Globox1997** [comment]
Pls update medievalweapons and betternether to the latest version
