### ISSUE TITLE
No data pack override for crafting recipes

### ISSUE THREAD

**Issue by Chribit** [Globox1997/MedievalWeapons#65]
I tried removing the crafting recipes for the wooden weapon variants by creating a data pack with appropriate recipes in a medievalweapons/recipes/ folder.

Taking a look at the contents of the jar, this would only work for the bows as no other recipes can be found in the corresponding folder.

Would be nice if all crafting recipes would be extracted to the crafting recipe data format of minecraft for full control via data pack. :)

**Comment by Globox1997** [comment]
Since the compatibility update, all recipes except those you mentioned are loaded through code but they should be able to get replaced still. 
If I remember correctly they are named just as the weapon ids like netherite_big_axe

**Comment by Chribit** [comment]
Cheers, I think I managed to do it eventually.

**Comment by Globox1997** [comment]
Glad to hear you figured it out :)
For other gamers, how did you do it?

**Comment by Chribit** [comment]
like you said, just added the correct crafting recipes i.e. json files with the correct names. :)
