### ISSUE TITLE
Two handed weapons don't display properly when main hand is set to left

### ISSUE THREAD

**Issue by purrfait** [Globox1997/MedievalWeapons#66]

**Comment by Globox1997** [comment]
Thanks for report, fixed with [https://github.com/Globox1997/MedievalWeapons/commit/1922c868b2288f29eb5a6ca3776a993404a15dec](https://github.com/Globox1997/MedievalWeapons/commit/1922c868b2288f29eb5a6ca3776a993404a15dec)
