### ISSUE TITLE
Mod not working on server

### ISSUE THREAD

**Issue by Shad0wzZYt** [Globox1997/MedievalWeapons#67]
When I try to join an Aternos server with this mod, I get the message : "Registry remapping failed: Received ID map for minecraft:mob_effect contains IDs unknown to the receiver! - medievalweapons:stun"

**Comment by Shad0wzZYt** [comment]
Nevermind, I just had an outdated version on my client

**Comment by Globox1997** [comment]
Glad you fixed it :)
