### ISSUE TITLE
Twilight Forest materials Compat

### ISSUE THREAD

**Issue by NotAlex17** [Globox1997/MedievalWeapons#71]
So I realized Twilight Forest was realeased for Fabric 1.18.  and I see that there is a lot of compatablity with other mods such as better end, better nether and Oh the biomes you'll go. So I was wondering if maybe you could add twilight forest materials to the mod now? I would love to swing around 2 firesteel ninjatos!

**Comment by Globox1997** [comment]
Reopen this issue with textures for a twilight forest compatibility.
