### ISSUE TITLE
Incompatiblity with BetterNether

### ISSUE THREAD

**Issue by Hasamanette** [Globox1997/MedievalWeapons#72]
1.18, Fabric0.13.3

heres the crashlog
[crash-2022-06-11_17.28.21-client.txt](https://github.com/Globox1997/MedievalWeapons/files/8884236/crash-2022-06-11_17.28.21-client.txt)
Would be great if a simple fix could arrange that

**Comment by Globox1997** [comment]
You have to install compatible versions of betternether and medievalweapons

**Comment by Hasamanette** [comment]
I tried loading differents versions of BetterNether and MedievalWeapons with also differents versions of bclib, just in case, and the result was the same every time

**Comment by Globox1997** [comment]
I recommend to update to 1.18.2 and use the latest versions of both mods

**Comment by Globox1997** [comment]
Out of time reasons I only work on the latest versions of my mods, which makes 1.18 not maintained
