### ISSUE TITLE
Weapon types

### ISSUE THREAD

**Issue by Valtyrian** [Globox1997/MedievalWeapons#73]
this mod doesn't sync well with the origins mod as every weapon is identified as a sword, even the axes which makes no sense. have you thought about changing this?

**Comment by Globox1997** [comment]
in what categories can the weapons get identified else?

**Comment by Valtyrian** [comment]
well you can add a axes.jason in this:
(https://github.com/Globox1997/MedievalWeapons/tree/1.19/src/main/resources/data/fabric/tags)/items/

divide them between axes and swords. weapons like daggers, staffs (which are basically sticks), and obviously swords would be in the sword.jason while axes (including fransisca), maces, and spears, can all be defined in the axes.jason

**Comment by Globox1997** [comment]
Which tag gets exactly used? what is its namespace?
c:swords and c:axes or something else?

**Comment by Valtyrian** [comment]
I would assume so. if you have the namespace for swords you would just have to replace swords with the word axes. I haven't written a mod before, but I have browsed through a lot of mod codes. (*I'm curious that way*). and seeing other weapon mods using different json's for each item type. and having the correct extends (ex: extends sworditem, extends axeitem)

**Comment by Globox1997** [comment]
the issue I see is, the axes aren't real minecraft axes, they are not intended to chop wood

**Comment by Valtyrian** [comment]
they don't have to be. hell, you can chop a tree with a Minecraft sword. use a Minecraft axe for combat. but anyone who uses the origin's mod and it's companion Medieval Origins. should they use a origin like Paladin who has a decrease on damage with swords and a damage buff with axes. all the weapons in your mod become useless. and you have some nice weapons to use too.

**Comment by Globox1997** [comment]
No plans to change it. Maybe origins provide something to determine between different weapons.
