### ISSUE TITLE
Compability with Better Combat by Daedelus

### ISSUE THREAD

**Issue by Raiguri** [Globox1997/MedievalWeapons#75]
Some weapons doesn't work with Better Combat at all, some looks just bad(like longsword and waraxes). 

![javaw_hyzJFKHOaG](https://user-images.githubusercontent.com/50903186/183306837-f9cbe32e-c9e8-4931-9f60-9d8d3d32f413.gif)
![javaw_OaEIZWkzXD](https://user-images.githubusercontent.com/50903186/183306841-998f2087-0c13-4794-a6d0-7860c7844bd1.gif)

**I know that its very easy to fix through Daedalus tutorial - https://github.com/ZsoltMolnarrr/BetterCombat#-integrate-your-mod**

**List of weapons that doesn't work properly:**
_Longswords, war axes, francisca, javelin, ninjato, and maybe dagger because his animations looks just kinda strange._

**Comment by Globox1997** [comment]
Working on it :)

**Comment by Globox1997** [comment]
Now done with [https://github.com/Globox1997/MedievalWeapons/commit/eb4656d4c057ab1564f9b0ed1947405db896e57a](https://github.com/Globox1997/MedievalWeapons/commit/eb4656d4c057ab1564f9b0ed1947405db896e57a)
