### ISSUE TITLE
[Crash] Javelin projectile collision with better physics ragdoll?

### ISSUE THREAD

**Issue by CasualJeremy** [Globox1997/MedievalWeapons#76]
https://gist.github.com/CasualJeremy/f1801239892b2057cc434f539338a19a

**Comment by Globox1997** [comment]
Looks like better physics tries to cast the javelin entity to a living entity with a mixin.
If I understand the crashlog correctly, the issue is not on my side, but I could be wrong.

**Comment by CasualJeremy** [comment]
You're right, I tested with only both mods and it had no issues. Time to figure this out one mod at a time. Thanks!
