### ISSUE TITLE
[Compatibility Request] Mythic Metals Support

### ISSUE THREAD

**Issue by cymophic** [Globox1997/MedievalWeapons#78]
Will it be possible for more weapons levels using mythic metal ores in the future?

**Comment by Globox1997** [comment]
If you want you can create the assets for the compatibility. Somebody else started it but only finished one set

**Comment by PixelatedBruh** [comment]
I have made assets for mythic metals and adabranium mod. adabranium is completely complete. i just need to make textures for mythic and i will have made complete compatibility.

**Comment by PixelatedBruh** [comment]
![2022-09-16_03 09 57](https://user-images.githubusercontent.com/54760551/190616121-b9653bc9-e2eb-41e3-aa92-c14cb6cac49f.png)

im not a texture artist so i cant make the best looking textures. and yes i already fixed the dot on the bronze ninjato

**Comment by Kuggle01** [comment]
Is there somewhere I can find the addon for mythic metals seen above?

**Comment by Kuggle01** [comment]
> ![2022-09-16_03 09 57](https://user-images.githubusercontent.com/54760551/190616121-b9653bc9-e2eb-41e3-aa92-c14cb6cac49f.png)
> 
> im not a texture artist so i cant make the best looking textures. and yes i already fixed the dot on the bronze ninjato

is there somewhere I can find this addon?

**Comment by PixelatedBruh** [comment]
unfortunately its not an addon as im just moddifying the original mod. i need to finish the rest of the textures and push it to the main owner so that they can add it.

**Comment by Kuggle01** [comment]
I see, well I hope it goes well, Medieval weapons with Mythic Metals support would literally be a dream come true for me

**Comment by Chriswa2k** [comment]
> ![2022-09-16_03 09 57](https://user-images.githubusercontent.com/54760551/190616121-b9653bc9-e2eb-41e3-aa92-c14cb6cac49f.png)
> 
> im not a texture artist so i cant make the best looking textures. and yes i already fixed the dot on the bronze ninjato

Holyy that looks amazing man, just created a github account to comment on that haha, is there any way i can find that addon now?

**Comment by Globox1997** [comment]
Reopen this issue when someone provides the textures :)
