### ISSUE TITLE
levelz Compat for Medieval Weapons Thrown Weapons

### ISSUE THREAD

**Issue by PixelatedBruh** [Globox1997/MedievalWeapons#80]
Thrown weapons like the javelin are not affected by levelz stat changes for damages. strength or archery have no affect on the thrown weapons damage

**Comment by Globox1997** [comment]
Thanks for the suggestion, added with [https://github.com/Globox1997/MedievalWeapons/commit/8d58777721401462a9bf694a1984fe4d94ee6364](https://github.com/Globox1997/MedievalWeapons/commit/8d58777721401462a9bf694a1984fe4d94ee6364)
