### ISSUE TITLE
Recipe list?

### ISSUE THREAD

**Issue by VoidPelt** [Globox1997/MedievalWeapons#81]
Is there a Wiki for the recipe's? Because I'm trying to make an Adamantine Longsword with the Mythic Metals mod in the Medieval MC modpack and I can't find the recipe.

**Comment by VoidPelt** [comment]
I can make any other of the mods weapons with Adamantite, but not a Longsword. The Recipe might actually be disabled in the mod's config.

**Comment by VoidPelt** [comment]
> I can make any other of the mods weapons with Adamantite, but not a Longsword. The Recipe might actually be disabled in the mod's config.

I can't find anything related to recipies in the configs

**Comment by Globox1997** [comment]
I think REI or EMI can help with that, not sure why the longsword doesn't work

**Comment by VoidPelt** [comment]
> I think REI or EMI can help with that, not sure why the longsword doesn't work

REI or EMI are NEI style mods right? Thing is tho ever other Longsword has a recipe except for the Adamantite Longsword. I asked the modpacks discord and they said you can't make it which is a bummer. So for right now until I can find a solution I will just spawn it in and get rid of the materials needed to make it by just using the wooden longsword recipe as a template.

**Comment by Globox1997** [comment]
Sounds like a compatibility issue, might be fixed in a later version of whatever mod.
reopen if still persistent.
