### ISSUE TITLE
Crashing on launch with the updated Mythic Metals v0.16.1

### ISSUE THREAD

**Issue by TalEdd** [Globox1997/MedievalWeapons#83]
[crash-2022-10-04_00.50.04-client.txt](https://github.com/Globox1997/MedievalWeapons/files/9699399/crash-2022-10-04_00.50.04-client.txt)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/5edcc2cd4f42668c4be46d57ccf958079c62e5bd](https://github.com/Globox1997/MedievalWeapons/commit/5edcc2cd4f42668c4be46d57ccf958079c62e5bd)
