### ISSUE TITLE
Textures Wont Load

### ISSUE THREAD

**Issue by GlitchedRaid** [Globox1997/MedievalWeapons#86]
When I tried to use this mod with BetterEnd, BetterNether, Back Slot, and Trinkets. The only textures that would load where the Francisca,   Ninjato, and Thalleous. I dont know what is going on
![image_2022-10-30_160959119](https://user-images.githubusercontent.com/117043599/198901724-5432037c-f81b-4e2d-8e81-3fb27d4c5f7b.png)
![image_2022-10-30_161015534](https://user-images.githubusercontent.com/117043599/198901741-ddce8f1c-8231-4513-bd28-d9c52438b102.png)
![image_2022-10-30_161033282](https://user-images.githubusercontent.com/117043599/198901762-75e2fff5-d40c-48de-a11a-7e686372f1ed.png)
![image_2022-10-30_161046663](https://user-images.githubusercontent.com/117043599/198901777-0d4a888e-879d-4e98-9463-94ab6413e9be.png)

**Comment by Globox1997** [comment]
Something is wrong here, which version of ARRP are you using?

**Comment by PhantomG27249** [comment]
Same issue and using the 1.19.2 build of BRRP 0.8.0 from curse forge

**Comment by EldrinFal** [comment]
Reporting the same issue as the others.  I'm also using BRRP 0.8.0 and Medieval Weapons 1.4.0.  I don't use Mythic Metals so I didn't upgrade to 1.4.1.  Also using Fabric Loader 14.10

**Comment by Globox1997** [comment]
Please use ARRP instead of BRRP, which can be found here [https://www.curseforge.com/minecraft/mc-mods/arrp](https://www.curseforge.com/minecraft/mc-mods/arrp)
Might update to BRRP someday if it won't get updated

**Comment by EldrinFal** [comment]
Unfortunately that one has it's own issues.  But yes, using ARRP does allow the models/textures of your mod to load.

https://paste.ee/p/XXAFD

Here is a copy of my log in case it can help.

**Comment by Globox1997** [comment]
What issues does ARRP have?

**Comment by EldrinFal** [comment]
https://github.com/Devan-Kerman/ARRP/issues

**Comment by GlitchedRaid** [comment]
> Something is wrong here, which version of ARRP are you using?

i dont know should i check the files

**Comment by TubXD** [comment]
> Please use ARRP instead of BRRP, which can be found here https://www.curseforge.com/minecraft/mc-mods/arrp Might update to BRRP someday if it won't get updated

Had the same issue, Fixed now thnx

**Comment by Eatham532** [comment]
Had the same issue. Maybe add this to the mod description for other people? Thanks

**Comment by Globox1997** [comment]
With the latest version ARRP and BRRP should work now but don't use both mods (even if they are included by other mods) at the same time.
