### ISSUE TITLE
Blocking is not disabled when cooldown starts (and other blocking issues)

### ISSUE THREAD

**Issue by BluStryx8** [Globox1997/MedievalWeapons#91]
If you take a hit while blocking with swords and axes, the block cooldown begins, but the weapon continues blocking so long as you continue holding the block button (unlike when hit by an axe, where you immediately stop blocking).
This means you can just shield hug for as long as you like with weapons that can block, and only have to worry about the cooldown once you release it. I'm not sure if this is intentional behavior or not.

Additionally, neither Battle Axes or War Axes disable shields at all, despite both being called axes. (unless they do in a pvp environment, but mobs definitely don't disable shields if they are holding these weapons, even though the vanilla axes will). This feels less intentional because it looks like there's configs referencing the battle axes and war axes and shield cooldowns.

**Comment by Globox1997** [comment]
do you have discord? Globox_Z #1024

**Comment by BluStryx8** [comment]
i do have discord, sent a request

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/496149c5b6822d3b9b39b22351d159723b5467ae](https://github.com/Globox1997/MedievalWeapons/commit/496149c5b6822d3b9b39b22351d159723b5467ae)

**Comment by GodlySlime** [comment]
@Globox1997 I need to talk to you thru discord
