### ISSUE TITLE
Blocking Animation breaks for 2 handed weapons with Better Combat installed [1.19.2]

### ISSUE THREAD

**Issue by Foxificer** [Globox1997/MedievalWeapons#94]
It worked fine on 1.18.2 but in 1.19+ this issue occurs.

When I block
![unknown32](https://user-images.githubusercontent.com/95505194/205165817-c32c7657-636f-408f-a868-5c4df81a2b80.png)

Without Blocking
![unknown33](https://user-images.githubusercontent.com/95505194/205165931-b9c6d6c2-aab3-4190-9703-3ecf722a8297.png)

**Comment by Globox1997** [comment]
Reopen if this still occurs in the latest version.

**Comment by Azu124** [comment]
Issue persists in 1.20.1 - v1.4.7

**Comment by kineticV** [comment]
@Globox1997 This is still an issue. The Better Combat author said that this mods needs to do something to integrate. Its broken in 1.19 too. Will this be fixed? https://github.com/ZsoltMolnarrr/BetterCombat/issues/160

**Comment by Hyxth** [comment]
I second this post. Two-handed blocking is broken with better combat in version 1.20.1 of minecraft.

**Comment by Globox1997** [comment]
Made a workaround with [https://github.com/Globox1997/MedievalWeapons/commit/274033423416f35f8efc0c89f5f964ecd9921260](https://github.com/Globox1997/MedievalWeapons/commit/274033423416f35f8efc0c89f5f964ecd9921260)
