### ISSUE TITLE
Says I don't have Cloth config but I do.

### ISSUE THREAD

**Issue by CaesarCarpathia** [Globox1997/MedievalWeapons#95]
![image](https://user-images.githubusercontent.com/120113599/206473581-71ddaa8c-f1e1-49de-810f-6c3865f851f4.png)
![image](https://user-images.githubusercontent.com/120113599/206474441-0ae84099-30bb-4787-82e6-cdaa41e72221.png)

**Comment by CaesarCarpathia** [comment]
-=

**Comment by Globox1997** [comment]
You need cloth config fabric

**Comment by CaesarCarpathia** [comment]
Oh I didn't look properly thanks
