### ISSUE TITLE
Blockable weapons decrease FPS in 3rd person

### ISSUE THREAD

**Issue by rtx2090ti** [Globox1997/MedievalWeapons#96]
https://user-images.githubusercontent.com/100720436/207971173-4e0626ca-b557-4aed-ab5b-1714c593bbfe.mp4

As seen in the video above

**Comment by Globox1997** [comment]
Do you use it with bettercombat?

**Comment by rtx2090ti** [comment]
> Do you use it with bettercombat?

Yes

**Comment by rtx2090ti** [comment]
Whoops-

**Comment by Globox1997** [comment]
Reopen if this still persist in the latest version.
