### ISSUE TITLE
Doesn't work on 1.19.3

### ISSUE THREAD

**Issue by SnowJay2005** [Globox1997/MedievalWeapons#98]
I'm sure you're probably already working on an update, but in case you didn't know that 1.19.3 broke the mod, thought I'd let you know

**Comment by Globox1997** [comment]
Almost all mods broke on 1.19.3 :) but I am not sure when I will update my mods to this version

**Comment by Globox1997** [comment]
I have no plans to update my mods to 1.19.3 and 1.19.4.
Mainly out of time reasons.
