### ISSUE TITLE
Medieval weapons possible incompatibility with nox 

### ISSUE THREAD

**Issue by RatDonkeyGoat** [Globox1997/MedievalWeapons#99]
[crash-2023-01-21_14.25.04-server.txt](https://github.com/Globox1997/MedievalWeapons/files/10474130/crash-2023-01-21_14.25.04-server.txt)

also i only ask about medieval weapons because of this reddit post

https://www.reddit.com/r/fabricmc/comments/yoo13b/fabric_server_keeps_crashing/?sort=new

**Comment by RatDonkeyGoat** [comment]
![Reason for crash](https://user-images.githubusercontent.com/30687395/214880796-0100b0b2-f7e8-45ca-aad4-bce6fafe2b78.png)

**Comment by RatDonkeyGoat** [comment]
[Problematic mixin .zip](https://github.com/Globox1997/MedievalWeapons/files/10510887/Problematic.mixin.zip)

**Comment by RatDonkeyGoat** [comment]
Files with a temporary fix
[EnchantmentHelperMixin.java.zip](https://github.com/Globox1997/MedievalWeapons/files/10510901/EnchantmentHelperMixin.java.zip)
[EnchantmentHelperMixin.class.zip](https://github.com/Globox1997/MedievalWeapons/files/10510902/EnchantmentHelperMixin.class.zip)
[medievalweapons-1.4.2.jar With Additional Additions corrected recipe and the fix for entities spawning with Enchanted Medieval Weapons temporary fix.zip](https://github.com/Globox1997/MedievalWeapons/files/10510903/medievalweapons-1.4.2.jar.With.Additional.Additions.corrected.recipe.and.the.fix.for.entities.spawning.with.Enchanted.Medieval.Weapons.temporary.fix.zip)

**Comment by RatDonkeyGoat** [comment]
https://github.com/Globox1997/MedievalWeapons/issues/30#issuecomment-1399158432 reason for Additional Additions corrected recipe

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/da9437820f51cea2d29dfb077539404e27d88fb2](https://github.com/Globox1997/MedievalWeapons/commit/da9437820f51cea2d29dfb077539404e27d88fb2)
